"""
SupernovaDataLoader
-------------------
Handles downloading, saving, and parsing the Supernova JSON data.
We download from Woflram Alfa Library, which has a specialized format of data storage.
That's why we have to add some extra parsing to clean it up, such as with the _clean_wolfram_string method

Classes:
    SupernovaDataLoader

Data Structures:
    - JSON byte stream from API
    - List[dict]: 
"""
import json
import requests
from src.constants import (
    SUPERNOVA_JSON_URL,
    JSON_FILENAME,
    LOG_FILENAME,
    WOLFRAM_STRING_QUOTE
)

class SupernovaDataLoader:
    """
    Handles downloading, saving, and parsing the Wolfram-formatted Supernova JSON data.
    """

    def fetch_and_save_json(self, url=SUPERNOVA_JSON_URL, target_filename=JSON_FILENAME):
        """Downloads the Wolfram-structured JSON to a local file."""
        try:
            response = requests.get(url)
            response.raise_for_status()

            with open(target_filename, "w", encoding="utf-8") as target_file:
                json.dump(response.json(), target_file)

            return target_filename
            
        except requests.RequestException as networkError:
            raise ConnectionError(f"Failed to fetch data from API: {networkError}") from networkError
        except IOError as fileWriteError:
            raise IOError(f"Failed to write JSON to {target_filename}: {fileWriteError}") from fileWriteError

    def parse_supernova_objects(self, source_filename=JSON_FILENAME):
        """Reads the local JSON file and extracts the nested Wolfram 'Association' blocks."""
        try:
            with open(source_filename, "r", encoding="utf-8") as source_file:
                raw_wolfram_dataset = json.load(source_file)

            # The Wolfram format is: ["Dataset", ["List", ["Association", [...]], ...]]
            wolfram_list_node = raw_wolfram_dataset[1]
            supernova_associations = wolfram_list_node[1:]

            return [self._convert_association_to_dict(node) for node in supernova_associations]
            
        except FileNotFoundError as missingFileError:
            raise FileNotFoundError(f"Source file {source_filename} not found: {missingFileError}") from missingFileError
        except (IndexError, TypeError, json.JSONDecodeError) as formatError:
            raise ValueError(f"JSON structure does not match expected Wolfram AST: {formatError}") from formatError

    def _convert_association_to_dict(self, association_node):
        """Translates a single Wolfram 'Association' array into a standard Python dictionary."""
        supernova_dict = {}
        
        try:
            rule_nodes = association_node[1:]  # Skip the "Association" string identifier

            for rule in rule_nodes:
                parsed_key = self._clean_wolfram_string(rule[1])
                parsed_value = self._clean_wolfram_string(rule[2]) if isinstance(rule[2], str) else rule[2]
                supernova_dict[parsed_key] = parsed_value

            return supernova_dict
            
        except IndexError as ruleParseError:
            raise ValueError(f"Invalid rule node structure in Wolfram Association: {ruleParseError}") from ruleParseError

    def _clean_wolfram_string(self, wolfram_string):
        """Strips the inner single quotes generated by Mathematica's JSON exporter."""
        return wolfram_string.strip(WOLFRAM_STRING_QUOTE)

    def log_objects_to_txt(self, supernova_objects, target_filename=LOG_FILENAME):
        """Writes parsed dictionary objects to a text file for validation."""
        try:
            with open(target_filename, "w", encoding="utf-8") as log_file:
                log_file.write("Logging Supernova Objects: \n")
                for supernova in supernova_objects: 
                    log_file.write(str(supernova) + "\n")
                    
        except IOError as logWriteError:
            # We don't raise here; a logging failure shouldn't crash the main pipeline
            print(f"Warning: Failed to write output log to {target_filename}: {logWriteError}")
